### PR TITLE
feat(component-update.sh): add script to update components

### PR DESCRIPTION
**Pull request by sabinem**
so far the script needs a tag, a branch and a component it will then update the component to use the latest commit in the client branch and give it a tag on the component. The tag can then be used to run the compoennt with the new version of the client in odtp.

The script is just in a basic version for now and can be improved later to take for example a list of components or find a usable tag on its own

### CODE REVIEW

**Comment by sabinem** [comment]
@caviri This is only a first version of the script, but it is already helpful: I will go about this in iterations: so please dev review.

**Comment by caviri** [comment]
Hello @sabinem, no problem. I think it's good. Maybe you can improve by introducing it in some `utils` or `script` folder. 

Also the removal of the `.gitignore` I think goes out of this PR. This client is never used individually so there should be any issue related to pushing `.env`. However, I think it is a good practice to have it there. At least for those `.DS_Store` files that some times macs place on repos.

**Review by caviri — APPROVED** [review]

**Comment by caviri** [comment]
Also, please can you add a small (one paragraph) description in the README?

**Comment by sabinem** [comment]
@caviri Thanks for the suggestions: very valid points and have been all addressed.

**Pull request merged**
